import React from "react";

export function FirearmsCodeContent() {
  return (
    <div className="lawyer-code-content criminal-code-content font-merriweather space-y-3">
      <div className="flex justify-center mb-6">
        <img src="/Legislation/DOJ Logo.png" alt="DOJ Logo" className="h-48 w-auto object-contain" />
      </div>
      <h1 className="text-[28px] font-bold text-center mb-2 text-black dark:text-white font-merriweather uppercase tracking-wide">CODE OF FIREARMS AND WEAPONS LAW</h1>
      <p className="text-[16px] font-normal text-center mb-8 text-[#5c6470] dark:text-[#9aa1b0] italic font-merriweather">(FIREARMS CODE)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.6</span>THE CODE OF FIREARMS AND WEAPONS LAW (Firearms Code)</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 1. General Provisions and Principles of the Firearms Code</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.1</span>The Code of Firearms and Weapons Law.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.1.1</span>The Code of Firearms and Weapon Law (Firearms Code) is a set of laws that regulates the lawful use, possession, sale and storage of Firearms, Weapons and Ammunition in the State of San Andreas.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.1.2</span>Any use of Firearms and/or Weapons in the State of San Andreas, including the use of State Issued Equipment by Employees of State Organisations, must comply with the Firearms Code and all other State Law.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.2</span>. Rules and Principles of the Code of Firearms and Weapons Law.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.2.1</span>The Principles and Provisions of the Firearms Code applies throughout the State of San Andreas and extends its legal force to all Citizens of the State and State Employees.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>In the event of a conflict or a need for clarification between provisions of the Firearms Code and any other State Law, or a conflict of provisions within the Firearms Code itself, the Supreme Court or the Attorney General shall make an Official Judicial Ruling as to the provisions that apply and the order of primacy of those provisions.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.2.2</span>Any Amendments to this Law by the Government or Judicial Rulings made by a Judge shall not apply retroactively and will only have force of law from the date of first application during a Trial or promulgation or publication as State Law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.2.3</span>The regulation of the distribution of all types of weapons and ammunition is managed by the National Guard (NG) and the government (GOV) in accordance with applicable state laws.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.3</span>Types of Armament in the state.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">There are seven types of armament in the State of San Andreas:</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.1</span>Melee weapons are items used to cause pain or injury to someone through the application of physical force in direct contact with the person.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: An object is considered a weapon only when it is used to threaten, intimidate, or harm another person. Possessing these items does not require a valid gun license.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.2</span>Firearms are weapons designed to strike a target at a distance using projectiles propelled by the energy from gunpowder or other charges. These include:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Pistols (such as handguns, vintage pistols, and armor-piercing pistols),</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Submachine guns (e.g., submachine guns, SMG submachine guns, SMG Mk II submachine guns, PDW submachine guns),</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Shotguns (standard shotguns, Mk II shotguns, and sawed-off shotguns),</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Assault rifles (including models like assault rifles, bullpup rifles, compact assault rifles, AUG rifles, SMG assault rifles, and specialized or extra versions),</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Thompson light machine gun,</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Unique light machine gun,</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Sniper rifles,</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Revolvers,</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Signal flare guns.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.3</span>Explosive weapons are devices that typically utilize high explosives to create a blast or fragmentation from the point of detonation, resulting in a powerful release of energy.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.4</span>Artillery weapons are large, long-range military arms designed to fire munitions over distances far greater than those of infantry firearms. They are limited in number within the National Guard&apos;s arsenal.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.5</span>Ammunition refers to the materials discharged, spread, released, or exploded from any weapon or weapon system. It is widely available for both civilian and military firearms.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.6</span>Bulletproof vests are pieces of body armor designed to absorb impact and minimize or prevent penetration of the torso by bullets fired from firearms or shrapnel from explosions.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">●</span>Owning bulletproof vests or body armor is permitted without the need for a valid firearm license. These items are commonly available in both civilian and military equipment.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.7</span>Weapon components are the parts used in the assembly and construction of weapons.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.4</span>Rules and Principles of the Right to Bear Arms.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.1</span>It is the Right of any Citizen of the State to possess Weapons, Firearms and Ammunition for those Firearms so long as they comply with the Laws for the Carry, Use and Storage of those Firearms. This applies for both civilian and service usage.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>This Right shall be revoked and all Weapons, Firearms and Ammunition shall be confiscated if the Citizen is to be Processed into the Department of Corrections (DOC) following Conviction of a Felony Crime or is otherwise found in violation of the Firearms Code.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.2</span>It is the Right of any Citizen of the State to use an appropriate Measure of Force in Defence of themselves or in Defence other Citizens of the State from an unlawful attack made against them.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>This shall not apply if the Citizen is intentionally interfering or trying to prevent the lawful Detention and/or Arrest of a Suspect by Law Enforcement Officers.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>This shall not apply if the Citizen is using any Measure of Force to prevent their own lawful Detention and/or Arrest during or following the commission of a crime.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>In the event of an unlawful or otherwise illegal Use of Force against the Citizen, they do have the Right to Defend themselves and their Right to Liberty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.3</span>It is the Right of any Citizen of the State to use an appropriate Measure of Force in the protection of their Private Property or any Shared Property that they are part of.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>This shall not apply in the event that the Citizen is intentionally interfering in the lawful execution of:</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>A Warrant of Search of that Property.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>A Search of a Property for a Suspect during a pursuit.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iii)</span>Any response to an Emergency Call (such as a House Robbery) at that Property by Law Enforcement Officers.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.4</span>These Rights may be revoked in the event that the Citizen has committed a Felony Crime that mandates the Confiscation of any License that permits the carry or purchase of those Weapons, Firearms and/or Ammunition.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.5</span>Rules and Principles of the Use of Firearms and Weapons.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.5.1</span>The use of any Weapons and/or Firearms must be preceded by a clearly expressed Warning to the person against whom the Weapons and/or Firearms may be used except in cases where any delay in the use of Firearms or Weapons creates an immediate or additional danger or risk to the life of the Citizen defending themselves or other Citizens of the State who are being defended.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.5.2</span>The use of Firearms or Weapons in any act of Defence should not cause harm to any Third Parties and/or innocent bystanders.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.6</span>Rules and Principles of the Use of Firearms and Weapons by a State Employee.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.6.1</span>A State Employee is permitted to use State Organisation Firearms, Ammunition and Equipment in the performance of their lawful duties to the State so long as they comply with the Firearms Code and all other State Law.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Employees of State Organisations are permitted to carry more than the limitations of this Firearms Code only while On-Duty.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Employees of State Organisations must still comply with these limitations while Off-Duty.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Employees of Emergency Medical Services (EMS) may not carry any Weapons, Firearms or Ammunition while On-Duty (exception can be made for a Torch for Rescue Services).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.6.2</span>A State Employee may carry a Personal Firearm and/or Weapon while On-Duty in addition to their State Organisation Firearms, Ammunition and Equipment so long as the use of that Personal Weapon complies with all other State Laws and the limitations for the Possession of Firearms and Ammunition.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Any Personal Firearm used must comply with the requirements or limitations in the Charter of their State Organisation and must be registered for use while On-Duty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.6.3</span>Law Enforcement Officers or Civil Servants must have a valid Bodycam of any incident where any Firearms or other Weapons are used against a Citizen of the State and must retain this Bodycam for 48-hours.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.7</span>Rules and Principles of the Sale or Transfer of Firearms and Weapons.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.7.1</span>A Citizen may transfer, donate or sell a Weapon, Firearm and/or Ammunition to another Citizen of the State so long as it is within the same limits defined by the Possession of Firearms and/or Ammunition and both Citizens own a Gun Licence.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 2. Basic Concepts and Definitions</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.1</span>Gun License.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.1</span>A Gun Licence (also referred to as a Firearms Licence or Licence to Carry a Weapon) is a Permit obtained by a Citizen of the State, giving them the right to buy, carry and use Legal Firearms and Weapons in accordance with this Code of Law and other State Law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.2</span>A Gun Licence is issued by the Government of the State (GOV) and any Citizen may apply for a Gun License according to the Procedure that has been set by the Government.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Government (GOV) has the right to set certain Conditions for the issue of a Gun Licence as well as the Price of a Gun License.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A Citizen may not transfer, donate or sell their Gun Licence to another Citizen of the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>It is the responsibility of all Citizens and State Employees to ensure that they have a valid Gun License and to renew their Gun License in good time.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.3</span>If a Citizen of the State does not possess a Gun Licence, then they have no lawful right to buy, own or use any Weapons, Firearms or Ammunition.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Any carry of any Firearms, Ammunition or Weapons without a Gun License is considered a Felony Crime.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Any provision for Self-Defence, Reciprocal-Defence or the lawful Defence of Property shall not apply if the Citizen claiming their actions were justified under those provisions did not at the time possess a Gun License.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.4</span>A gun license may be revoked and canceled in the event of any violation of this Firearms Law or if specified in the Penal Code.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.5</span>A Gun License cannot be issued without valid medical insurance.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.2</span>Legal Firearms and Weapons.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.2.1</span>Legal Firearms and Weapons only includes items with a visible AMMO Serial Number (indicated with a Number and the letters AMMO eg: 1234567 (AMMO).</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.3</span>Illegal Firearms and Weapons.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.1</span>All Firearms with a scratched Serial Number (indicated with the marking “XXX”) are considered Illegal Firearms, regardless of their origin.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: This applies to all painted weapons and those with scratched-off serial numbers [XXX].</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.2</span>Weapons with serial numbers that include a state organization identifier are considered illegal for anyone not employed by that organization.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.3</span>Any provision for Self-Defence, Reciprocal-Defence or the lawful Defence of Property shall not apply if the Citizen is using any Illegal Firearms.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.4</span>Illegal weapons are prohibited from use and must be surrendered for destruction.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: This also forbids usage by Law Enforcement Agencies.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.4</span>State Organisation Firearms and Equipment.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.4.1</span>State Organisation Firearms, Ammunition and Equipment is the property of the State and the use or possession of any State Organisation Firearms and/or Equipment by a Civilian is strictly prohibited.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.4.2</span>State Organisation Firearms and Equipment includes, but is not limited to:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Any Balaclava, regardless of origin.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Any EMS Medical Mask.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>All Firearms, Body Armour and Equipment marked as the property of a State Organisation or any items with the following markings:</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Emergency Medical Services (EMS)</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>Federal Investigation Bureau (FIB)</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iii)</span>Government (GOV)</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iv)</span>Los Santos Police Department (LSPD) or marked with Central Police (CP)</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">v)</span>National Guard (NG)</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">vi)</span>San Andreas Highway Patrol (SAHP)</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.5</span>Weapons, Ammunition and Firearms as Crime Scene Evidence.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.5.1</span>Any Firearms or quantity of Ammunition recovered as Evidence from a Crime Scene may be retained by the Law Enforcement Officer to be used as Evidence until no longer required for this purpose.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.5.2</span>It is not a Felony Crime for a Law Enforcement Officer to possess any Illegal Firearms that have been recovered to be used as Evidence, so long as valid Bodycam of the Crime Scene and where the Illegal Firearms were found can be provided when required by a Judge or Lawyer.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.5.3</span>The Law Enforcement Officers and/or Civil Servants must dispose of any Illegal Firearms and/or Weapons at the Front Desk of their Headquarters or should discard the Items in the presence of the Judge or Lawyer as soon as no longer required as Evidence.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.6</span>Legal and Illegal Ammunition.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.6.1</span>Ammunition is not marked in any way and the legality and/or origins of any Ammunition cannot be proved to be legal or illegal under the law, except in clear cases of theft from the Armory of a State Organisation or failure to return Ammunition to the Armory of a State Organisation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>In the event that a State Employee accidentally returns personal Ammunition to a State Armory, they have no claim or right to take this Ammunition back once returned and this shall be regarded as theft.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.7</span>Open Carry.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.7.1</span>Civilians are prohibited from openly carrying any type of weapon, and doing so incurs legal liability. This also applies to carrying weapons in pockets or in a holster under outer clothing for quick access.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Law Enforcement Officers and Civil Servants have the right to request a show of Licenses from any Citizen who has been seen with an Open Carry Firearm or Weapon.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.7.2</span>The open wearing of any Body Armour or Vest without a clear valid reason shall also be considered a form of Open Carry.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.7.3</span>Open carrying of a service weapon must be justified by the existence of valid reasons for its immediate use.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 3. Laws for the Possession and Storage of Firearms and</h2>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Ammunition</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">3.1</span>Possession of Firearms and Ammunition.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.1.1</span>A Citizen of the State with a Gun License is permitted to carry:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Individuals are allowed to possess no more than one legal firearm and a total of 100 rounds of ammunition.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.1.2</span>Any carry of more than the above permitted limits is considered a Felony Crime and shall result in Criminal Charges and Confiscation of all Items as well as the Gun License in accordance with this Firearms Code and the Criminal Code.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Employees of State Organisations are permitted to carry more than these limitations only while On-Duty in order to perform their lawful duties to the State.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>All Employees of State Organisations must still comply with these limitations while Off-Duty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.1.3</span>Any possession, use or storage of any Weapons, Firearms and/or Ammunition without a Gun License is considered a Felony Crime and shall result in Criminal Charges and Confiscation of the Firearms and/or Ammunition in accordance with this Firearms Code and the Criminal Code.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.1.4</span>Employees of state organizations are permitted to carry only one personal weapon while on duty. This weapon must be logged and approved by high command.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">3.2</span>Possession of State Organization Firearms, Ammunition and Equipment.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.1</span>State Organization Firearms, Ammunition and Equipment is the property of the State and is reserved for carry and use by State Employees only:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>While that State Employee is On-Duty and,</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>While that State Employee is wearing a Uniform of their State Organisation.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>An exception to the above provisions must be allowed directly following a State Employee being out of Uniform due to any unavoidable circumstances (eg: sent to the Hospital or a Code A).</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>It is the obligation of the State Employee to remove any visible State Equipment and to return to Active Duty and to change into their Uniform, or to return any State Organization Firearms, Ammunition and Equipment if they will not be resuming Active Duty, as soon as reasonably possible.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Where a State Employee of the Federal Investigation Bureau (FIB) or Government (GOV/USSS) is working Undercover, the carry of any State Issued Firearms, Ammunition and Equipment is only permitted under the regulations for Undercover Agents as defined in the Charter of that State Organisation.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The State Employee must be able to prove that they are authorized to work Undercover at that time and they are On-Duty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.2</span>State Employees must have a valid Gun License in order to take or carry State Issued Firearms, Ammunition and Equipment from the Armory of their Organization.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>In the event that a State Employee is found to not be in possession of a valid Gun License, they must immediately return all State Issued Firearms and Equipment to the Armory and must obtain a Gun Licence before resuming Active Duty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.3</span>It is strictly prohibited for Employees of a State Organisation or any Civilian:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>To sell or attempt to Sell State Organization Firearms, Ammunition and Equipment.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>To transfer or donate State Organization Firearms, Ammunition and Equipment to a Civilian.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>To carelessly discard or dispose of State Organization Firearms, Ammunition and Equipment.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>To place or store State Organization Firearms, Ammunition and Equipment in a Personal Vehicle or Family Vehicle.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>To place or store State Organization Firearms, Ammunition and Equipment in the warehouse of a Private Property or Shared Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.4</span>Each state employee is personally accountable for any service weapon they receive from their organization and can be held criminally liable for its misuse or loss.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.5</span>A State Employee may transfer or donate State Organization Firearms, Ammunition and Equipment to another State Employee in the event of an emergency situation or an urgent need.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Where possible such State Organization Firearms, Ammunition and Equipment should be returned to the proper State Organisation as soon as the emergency situation has passed.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Any State Organization Firearms, Ammunition and Equipment that have been transferred or donated under this provision should be documented and Evidence should be retained for 48-hours in the event of an Investigation.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.6</span>At the end of a shift, when leaving for lunch, or in any off-duty situation that involves not wearing the official uniform approved by the organization&apos;s dress code, a civil servant must return all service weapons to their organization. They are not permitted to carry any service armament, either on their person or in their vehicle. Exception: Employees may be authorized to carry organizational equipment after their regular work shift, in accordance with section 3.2.1 of the Firearm Law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.7</span>A careless or disrespectful attitude towards service weapons and/or state-issued protective gear is strictly forbidden and may result in criminal liability.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: Breach of this article is considered Professional Misconduct.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.8</span>The regulation of service weapon circulation is managed by authorized personnel (FPS) within each state organization or by the Attorney General&apos;s Office.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.2.9</span>. Undercover agents of the Federal Investigation Bureau assigned a task are allowed to carry only one weapon, along with 150 rounds of ammunition and one set of body armor. If an undercover agent is found carrying more than this specified amount, they will be charged under section 2.17.2 for Excessive Firearms Carry (Overcarrying), classified as a Class-4 Felony, and will face a 10-day suspension from the Federal Investigation Bureau.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">3.3</span>Storage of Firearms and Ammunition in a Vehicle.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.3.1</span>A Citizen of the State with a Gun License is permitted to store (in total):</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>No more than 3 x Legal Firearms in a Vehicle and/or:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A maximum total of 300 bullets in a Vehicle for any type of Firearm (not for each Firearm).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: Members of state organizations who possess a valid Military ID are allowed to carry double the specified amounts of firearms and ammunition in their personal vehicles, as long as the vehicle is not owned by a family member.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.3.2</span>Any storage of more than the above permitted limits is considered a Felony Crime and shall result in Criminal Charges and Confiscation of all Items as well as the Gun License in accordance with this Firearms Code and the Criminal Code.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.3.3</span>All Weapons, Firearms and Ammunition stored in the trunk of a Vehicle are the responsibility of the Driver of the Vehicle.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Where the Driver is not at the scene, the Owner of the Vehicle may not be subject to Felony Charges or placed on the Wanted List following a Search of the Vehicle, but may be issued the relevant Fine(s) for the violation of the law if the Search of the Vehicle was lawful.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Law Enforcement Officers are required to retain any Evidence of the situation for a minimum of 48-hours and be able to prove that the Search was lawful in the event of an Investigation by the Department of Justice (DOJ).</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">3.4</span>Storage of Firearms and Ammunition in a House, Apartment or backpack.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.4.1</span>There is no legal limit to the secure storage of Firearms and Ammunition in the Warehouse of a Private Property or a Shared/Family House or Apartment.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.4.2</span>The carrying and storage of authorized firearms is permitted in a backpack, in the trunk of a vehicle, and at a civilian&apos;s permanent residence, provided they are stored unloaded and secured in a specially equipped locker with a safety lock.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: The acquisition, carrying, use, and storage of a taser are prohibited for all civilians and are governed by section 2.17.5 regarding the Possession of State-Issued Items.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 4. Laws and Procedures for the Lawful Use of Force by Citizens</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">4.1</span>Rules and Principles of the Right to Defence of Self (Self Defense).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.1.1</span>Self-Defense is a legal principle that permits the Use of Force to protect oneself from attempted attack, harm or injury by another Citizen of the State.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.1.2</span>In order for a Party to a Case or Trial to claim Self-Defence, that Party must have met the following necessary requirements:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Party must be confronted with an unprovoked attack against themselves.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Party must not have actively placed themselves in a dangerous situation (eg: running into an ongoing shootout).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The Party must be under imminent threat of injury or death.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>The Party must have an objectively reasonable fear of injury or death.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>The Degree of Force used in Self-Defense must be reasonable under the circumstances.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>A victim should not respond with Lethal Force when engaged with any lesser Measure of Force unless there is no other reasonable option to defend themselves or to safely leave the situation.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">4.2</span>Rules and Principles of the Right to Defence of Others (Reciprocal or Mutual Defence).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.2.1</span>Mutual or Reciprocal Defense is a type of Defense that includes the protection of a Citizen who is deprived of the opportunity to defend themselves from an unlawful attack.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.2.2</span>In order for a Party to a Case or Trial to claim Reciprocal Defense, that Party must have met the following necessary requirements:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Victim must be confronted with an unprovoked attack against themselves.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Victim must not have actively placed themselves in a dangerous situation (eg: running into an ongoing shootout)</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The Victim must be under imminent threat of injury or death.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>The Party that acted in Reciprocal Defense must have an objectively reasonable expectation that injury or death of the Victim may result if they do not Defend the Victim.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>The Degree of Force used in Reciprocal-Defense must be reasonable under the circumstances</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The Defending Party should not respond with deadly force when a Victim is engaged with non-deadly force unless there is no other reasonable option to defend the Victim.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">4.3</span>Rules and Principles of the Right to Defence of Private Property.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.3.1</span>The Owner of a Property has the lawful right to protect their Private Property from unlawful attempts at trespassing, unlawful entry into the House and/or any attempt at theft from their Private Property.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A Private Property includes the Driveway of the Property and the area of a Property immediately adjacent to the Property enclosed by any structures such as pillars, walls, hedges or fences surrounding the Property as well as the interior of any House or Building on the Property.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Where the Property is an Apartment Block or Tenement Block without clearly defined Property boundaries or shared boundaries the Court shall determine the boundaries after evaluation of the specific Property.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A Private Property does not include the public streets and the sidewalks in front of or adjacent to the Private Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.3.2</span>A Citizen may only claim Defence of Private Property if they have first given a clear Verbal Warning or Demand for the trespasser(s) or intruder(s) to leave their Property.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">4.4</span>Rules and Principles of the Right to Defence of Shared Property.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.4.1</span>The Members or other stakeholders in a Shared Property (including Family, Corporate or Communal Property) have the lawful right to protect their Property from unlawful attempts at trespassing, unlawful entry into the House and/or any attempt at theft from their Property.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A Shared Property includes the Driveway of the Property and the area of a Property enclosed by any structures such as pillars, walls, hedges or fences surrounding the Property as well as the interior of any House or Building on the Property.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Where the Property is an Apartment Block or Tenement Block without clearly defined Property boundaries or shared boundaries the Court shall determine the boundaries after evaluation of the specific Property.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A Shared Property does not include the public streets and the sidewalks in front of or adjacent to the Private Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.4.2</span>A Citizen may only claim Defence of a Shared Property if they have first given a clear Verbal Warning or Demand for the trespasser(s) or intruder(s) to leave the Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.4.3</span>A Citizen may only claim Defence of a Shared Property if they are able to prove their Claim to being a Member or a stakeholder in the Shared Property.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 5. Laws and Procedures for the Lawful Use of Force by the State</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.1</span>Rules and Principles of Necessity and The Use of Force During Detention and/or Arrest.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.1.1</span>In case of the need to use force during a Detention or Arrest, a Law Enforcement Officer or Civil Servant is required to adhere to the Principles of Necessity and wherever possible: or Arrest.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Note: Law enforcement officers are encouraged to use a taser prior to resorting to a lethal weapon, except in situations where the suspect is armed, hostile, or poses an immediate threat to life.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>To only use as much force as necessary, given the circumstances.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>To limit the Use of Force in relation to the actions of the Suspect to whom they are applied.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>To limit the Degree of Force in relation to the Degree of Threat.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>To only use Lethal Force against the intended Suspect.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>To only use Lethal Force where the law permits the use of Lethal Force.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.1.2</span>Where any Damaging, Harmful or Lethal Force has been used, Law Enforcement Officers must provide on-scene first aid to the Suspect as soon as reasonably possible.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.1.3</span>Any other Use of Force outside of these requirements or other conditions set out in this Firearms Code or the provisions of the Criminal Code may be considered a violation of the law and may result in Civil or Criminal Liability.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.2</span>Rules and Principles of the Use of Excessive Force.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.2.1</span>Where the circumstances or the actions of a Suspect limit the available means to resolve a situation through the use of lesser Stages of Force, Law Enforcement Officers and/or Civil Servants of the State may use a higher Tier of Force:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Only to resolve the immediate situation at hand.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Only if the Suspect is in a clear violation of the law.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Only if no other options are possible to resolve the situation (for example: a Suspect refusing to step out of a vehicle or a Suspect remaining armed when ordered to put away their weapon).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.2.2</span>In this situation any Use of Force must be clearly stated as a Warning beforehand, unless the Suspect is a Direct Threat or remains Armed and Dangerous.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A Warning Shot may also be fired to indicate that Lethal Force may be used against the Suspect.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.2.3</span>All Excessive Use of Force outside of these requirements may be considered a violation of the law and may result in Civil or Criminal Liability.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.3</span>Use of Restraining Force.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.3.1</span>Restraining Force is defined as the use of any Measure of Force which limits or prevents a Citizen’s ability to take any actions or to move and involves the use of Handcuffs and (if required) Holding or Leading the Suspect by the arm.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.3.2</span>Restraining Force may be used if it is necessary to ensure compliance with a lawful order, to forcibly remove a Citizen from a crime scene or situation if necessary or to Detain and/or Arrest a Citizen.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The use of Handcuffs and/or Holding the Citizen may be used to control or prevent a situation where there is a reasonable suspicion that the Citizen may interfere in a Detention and/or Arrest but has not yet committed any violation of the law.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The Law Enforcement Officer should clearly state that the Citizen is only being Restrained and is not being Detained and/or Arrested.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.4</span>Use of Immobilising Force.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.4.1</span>Immobilising Force is defined as the use of any Measure of Force that uses debilitating attacks and does not cause physical harm or damage to a Suspect (such as a Stun Gun or Taser).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Immobilising Force should always be the first option considered by Law Enforcement Officers against an unarmed Suspect unless a higher Measure of Force is required or is necessary under the circumstances.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.4.2</span>Immobilising Force may be used by Law Enforcement Officers and Civil Servants on the following Grounds:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>On the Grounds of Failure to Comply. Immobilising Force may be used against an unarmed Suspect who does not comply with a lawful order of a Law Enforcement Officer or Civil Servant and who needs to be immobilized before being Handcuffed, Held by the Arm or Restrained by the Law Enforcement Officer.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>On the Grounds of Escape or Attempted Escape. Immobilising Force may be used against an unarmed Suspect who attempts to flee the scene of a crime or escape from any form of Custody (Detention or Arrest) or Imprisonment.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>On the Grounds of Damage to Property. Immobilising Force may be used against an unarmed Suspect who is intentionally causing unlawful damage to Property and whose further actions need to be stopped.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.5</span>Use of Damaging or Harmful Force.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.5.1</span>Damaging or Harmful Force is defined as the use of all Measures of Force that cause physical damage but are not immediately considered Lethal Force. Damaging Force includes Unarmed Attacks (punching, kicking) and Close Combat Weapons such as batons/nightsticks.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.5.2</span>Damaging or Harmful Force may be used where necessary against a Suspect and where Lethal Force would be considered unlawful or excessive on the following Grounds:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>On the Grounds of Self-Defence. In the event of an intentional attack on the Law Enforcement Officer or Civil Servant that causes physical harm, Damaging or Harmful Force may be used where Lethal Force is not necessary or would otherwise be considered excessive.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>On the Grounds of Reciprocal-Defence. In the event of an intentional attack on any Citizen of the State that causes physical harm, Damaging or Harmful Force may be used where Lethal Force is not necessary or would otherwise be considered excessive.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.6</span>Use of Lethal Force.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.6.1</span>Lethal Force is defined as the use of any Firearms, or the continued use of Damaging or Harmful Force only where continued use is necessary.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.6.2</span>Lethal Force should not be used in an arbitrary manner and may only be used on the following Grounds and should, where reasonable, be preceded by a clear Warning.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>On the Grounds of Self-Defence. In the event of an intentional attack on the Law Enforcement Officer or Civil Servant that may result in a risk to their life or unconsciousness, Lethal Force may immediately be used without any Warning.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>On the Grounds of Reciprocal-Defence. In the event of an intentional attack on any Citizen of the State that may result in a risk to their life or unconsciousness, Lethal Force may immediately be used by Law Enforcement Officers or Civil Servants without any Warning.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>On the Grounds of a Direct Threat. Lethal Force may be used to prevent a clear and intentional threat or risk to the life of a Law Enforcement Officers, Civil Servants and other Citizens of the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>On the Grounds of a Suspect Being Armed and Dangerous. Where a Suspect remains armed and does not put away their Weapon when ordered to, or draws a Firearm or Weapon with the intent to attack by pointing the Firearm at another Citizen, the Suspect is considered Armed and Dangerous and Lethal Force is immediately authorized to neutralize the possible threat they pose to Law Enforcement Officers, Civil Servants and other Citizens of the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>On the Grounds of State Security. The Use of Lethal Force is immediately authorized without the normal requirements for the Use of Force or any Warning by the United States Secret Service (USSS) as well as all Employees of the Government (GOV) in the event of any risk or threat to the life or safety of a First Person of the State or a Government Official.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">f)</span>On the Grounds of Military Security. The Use of Lethal Force is immediately authorized to be used in the defense of Fort Zancudo by the National Guard (NG) and State Employees assisting the National Guard without the normal requirements for the Use of Force in the event of any Citizen entering or trespassing within the Restricted Zone (Red Zone) of Fort Zancudo without permission or prior authorisation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">g)</span>On the Grounds of Escape or Attempted Escape. Where the Use of Immobilising Force fails or is not possible in the circumstances, Law Enforcement Officers and Civil Servants may use Lethal Force in order to prevent the escape of a Suspect.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>At least one clear verbal Warning should be given before Lethal Force is used on a Suspect who is clearly Evading Detention and/or Arrest or is attempting to Escape from Custody (eg: “Stop or I will Shoot”).</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>Where a Suspect may not hear a verbal Warning, a Warning Shot may be fired in addition to the verbal Warning.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iii)</span>If a Suspect cooperates with the order to stop, Lethal Force must not be used unless the Suspect remains a Direct Threat or is Armed and Dangerous.</p>

      <div className="text-center mt-12 mb-8 font-merriweather border-t border-black/20 dark:border-white/20 pt-8">
        <p className="text-black dark:text-white font-bold text-[18px] uppercase tracking-wider mb-6">Signed into Legislation By</p>
        <div className="my-6">
          <p className="font-dancing text-black dark:text-white text-[32px] leading-none mb-1">Tony Accordo Attorney General of the State of San Andreas Zoro Saturo Governor of the State of San Andreas</p>
        </div>
      </div>

      <h2 className="text-[20px] font-bold mt-12 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather text-center">Credit and Copyright</h2>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">This work, and the others in this series of legislative enhancement are produced and promulgated in the interests of justice and the promotion of the legal rights of all Citizens of the State of San Andreas. Second Edition revised and amended in the 10th Month of 2024 by Mohil Yami, Attorney General of the State of San Andreas on the advisory of Governor Zoro Satoru. All Articles of this Code of Firearms and Weapon Law reviewed and amended by Attorney General Poppy Lasombra in the 5th Month of 2023. Work completed in the 6th Month of 2023. Originally derived from work laid out by the Whitewind Law Office, Lane Stevens, and Ni Bjeebies from another city with a great history.</p>

      <h2 className="text-[20px] font-bold mt-12 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather text-center">Version History and Changes</h2>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">First Edition. Published on the 1st of July 2023.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(27/01/2023)</span>First Edition formally changed the Firearms Code to the Code of Firearms and Weapon Law (Firearms Code) in keeping with the naming convention of all Updated Laws. Changes to the format of the Firearms Code in keeping with all Updated Law Format.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(27/01/2023)</span>Article 1. Clarified the Principles of Firearms Law. Removed all Unnecessary Descriptive Sections. These are considered Dead-Letter Law as explosive devices and other descriptions are not relevant in the State. Further removed 2.2 and 2.3 as these were not valid and are descriptive of things that are not possible in the city and are not prescriptive as law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(27/01/2023)</span>Article 1.3 Added and Clarified the Right to Bear Arms as a Right of all Citizens so long as they comply with this Code of Law and the law for the Use of Firearms.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(25/05/2023)</span>Added 1.6 Rules and Principles of the Sale of Firearms and Weapons. It is commonplace for Civilians to share a weapon with family members for activities and this should not be considered illegal so long as the laws for possession and use are followed (1 x Legal Gun and 50 ammo maximum).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Amended 2.1 Possession of Firearms and Ammunition. Allowed a close combat weapon to be carried in addition to the current gun and ammo limitations. This is to allow for the proper use of force when possible in Self-Defence and might improve some RP of these situations. Previously it was not possible to carry a gun AND a close combat weapon making all situations use firearms (excessive force)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(27/05/2023)</span>Clarified 2.3 Storage of Firearms and Ammunition in a Residence. There has never been any actual limit to this defined in the law nor is it possible for Law Enforcement Officers to Search a Warehouse in a House.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(22/05/2023)</span>Article 4 Redefined and Clarified the Principles of Self-Defence, Reciprocal Defence and Property Defence. Clarified that this does not include public streets and sidewalks next to a house.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/04/2023)</span>Repealed 3.10 The use of any type of civilian weapon on duty is strictly prohibited for all State employees. Exception : approved undercover agents, EMS employees. This has not been enforced and is considered Dead Letter Law. It has long been permitted for a LEO to use a Revolver and many use a Circumcised Shotgun instead.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(22/05/2023)</span>Added 1.5 Rules and Principles of the Use of Firearms and Weapons by a State Employee. Clarified that a State Employee can use their Civilian Firearm (such as a Revolver) while On-Duty but must comply with all normal laws for the use of that Firearm (max 1 x Legal Weapon and 50 x Ammo etc).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Added 1.5 Rules and Principles of the Sale of Firearms and Weapons. It is legal to do (and is often done before Family Events) but there must be limits and these are set as the same limits as possessing a firearm.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(08/05/2023)</span>Clarified 2.1 Gun License. Added provision that any use of Firearms (Self Defence etc) is illegal if they have no Gun Licence.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/06/2023)</span>Clarified 2.2 Legal Firearms and Weapons, 2.3 Illegal Firearms and Weapons and 2.3.2 Painted Firearms or Firearms</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/05/2023)</span>Added Clarification 2.4 Legal and Illegal Ammunition. Ammo is not marked and cannot be seen to be legal or illegal unless in violation of other laws (eg: Overcarrying).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Clarified 2.5 State Issued Firearms and Equipment and added list of the State Org markings.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Added 2.8 Weapons, Ammunition and Firearms as Crime Scene Evidence. Due to officers being unfairly Charged with possession of illegal firearms, a provision needed to exist for their temporary use as Evidence and they must be disposed of as soon as no longer required.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Clarified 2.1 Possession of Firearms and Ammunition. Added provision for the carry of a close combat weapon due to clarifications of the use of force.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Clarified 2.1.2 a) State Employees can carry more than is permitted only while On Duty. May not do this when Off-Duty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/06/2023)</span>Changed 2.1.2 b) Previously the law indicated that EMS were allowed to actually carry a weapon on duty as per the old Gun Law but this is illogical and, by the internal regulations of EMS, clearly not allowed.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Clarified 2.2 Possession of State Organization Firearms, Ammunition and Equipment. Added Provision 2.2.1 c) for State Employees who are in Hospital (they will have items while not in Uniform)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Added 2.2.4 as a provision for transfer of State Equipment during an Emergency or Event. This is due to State Employees being unfairly Arrested and needed to be clarified in the law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Clarified 2.5 Storage of Firearms and Ammunition in a House or Apartment. There is no limit.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(19/05/2023)</span>Clarified 4.1 Rules and Principles of the Right to Defence of Self (Self Defence).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(19/05/2023)</span>Clarified 4.2 Rules and Principles of the Right to Defence of Others (Reciprocal or Mutual Defence).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/05/2023)</span>Clarified 4.3 Rules and Principles of the Right to Defence of Private Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(20/06/2023)</span>Clarified 4.4 Rules and Principles of the Right to Defence of Communal Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(21/06/2023)</span>Added clear definition of the boundaries of a Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/04/2023)</span>Moved Article 5. Laws and Procedures for the Lawful Use of Force by the State from the Civil Code to the Firearms Code. It makes more sense to be considered part of the State Laws dealing with Firearms and the use of them</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(11/05/2023)</span>Moved and Clarified 5.1 Rules and Principles of Necessity and The Use of Force During Detention and/or Arrest.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(12/05/2023)</span>Added 5.2 Rules and Principles of the Use of Excessive Force. The options for LEOs are sometimes limited and strict laws need to exist when excessive force can be used.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(16/04/2023)</span>5.3 Use of Restraining Force. Added provision and laws for Restraining a Citizen (which is not an Arrest or Detention) using Handcuffs as the only possible type of Tier 3 Force that exists. (Previously the law stated things like arm-locks can be used but these do not exist)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(16/04/2023)</span>5.4 Use of Immobilising Force. Defined Immobilizing Force and clearly indicated that this form of force should be the default method used unless higher forms are necessary.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(22/06/2023)</span>Clarified 5.5 indicating when Tier 4 (Severe/Damaging/Harmful Force) can be used.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(22/06/2023)</span>Clarified 5.6 Use of Lethal Force indicating when Lethal Force can be used. Law Enforcement Officers use Lethal Force too often, even when it is not permitted and clear Grounds and limitations were needed Second Edition. Published on the 10th of October 2024.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Clarified 1.2.1 a) The Supreme Court or the Attorney General shall make an official judicial ruling for any conflicts in the Firearms Code.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.2.3 Regulation of the distribution is managed by the National Guard (NG) and the government (GOV).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3 types of Armament. Explained each type of Armament in the state.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.1 Use of melee, and when can it be used as a weapon? no license is required for the ownership or use of melee weapons, unlike firearms.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.2 Specified all types of firearms.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.3 Explained about explosive weapons.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.4 Explained about artillery weapons.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.5 Explained about ammunition.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.6 Explained about bulletproof vest, no license is required for the ownership or use of bulletproof vest, unlike firearms.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(01/10/2024)</span>Added 1.3.7 Mentioned components of weapons are part of construction of weapons.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Changed Article Number 1.3 to 1.4, 1.4 to 1.5, 1.5 to 1.6 and 1.6 to 1.7.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Clarified 1.4.1 This principle applies for both civilian and service usage.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Added 2.1.4 Explained, when can a gun license be revoked?</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Added 2.1.5 Gun license cannot be distributed without proper medical insurance.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Added 2.3.1 All painted weapons and scratched off serial numbers weapons are considered illegal</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Added 2.3.2 Any weapon with organization serial number is considered illegal if it is in possession of any other organization member.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Changed Article number 2.3.2 to 2.3.3.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Added 2.3.4 Illegal weapons are prohibited to use and must be destroyed.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Removed Article 2.4 Unnecessary descriptive section.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(02/10/2024)</span>Changed Article Number 2.5 to 2.4, 2.6 to 2.5, 2.7 to 2.6 and 2.8 to 2.7.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(03/10/2024)</span>Added and clarified 2.7.1 Civilians are not permitted to carry any weapon openly, and it cannot be used, or in a holster under outer clothing for quick access.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(03/10/2024)</span>Added 2.7.3 Open carry of any service weapon must be justified.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(03/10/2024)</span>Added and clarified 3.1.1 a) Increased the number of ammunition that an individual can possess to 100.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(03/10/2024)</span>Removed 3.1.1 b) conflict with updated laws.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(03/10/2024)</span>Added 3.1.4 Employees of state organizations can only possess one personal weapon while On-Duty.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Added 3.2.4 Clarified that each employee is responsible for their service weapon and will be held liable for the misuse.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Changed Article number 3.2.4 to 3.2.5.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Added 3.2.7 Clarified that employees of state organizations cannot carry any service weapons after their shift or breaks.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Added 3.2.8 Clarified that any disrespect towards the service weapons will be held responsible for professional misconduct.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Added 3.2.9 Clarified the regulation of service weapon circulation is managed by each organization FPS and by the Attorney General&apos;s Office.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Added 3.2.10 Specified how much amount can undercover agents carry service weapons.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Clarified 3.3.1 b) Increased number of ammunition can be stored in personal vehicles up to 300.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Clarified 3.4 Storage of Firearms and Ammunition in a House, Apartment or backpack.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Added 3.4.2 Specified the storage of weapons in personal space and clarified the use of tasers is prohibited for all citizens.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(04/10/2024)</span>Clarified 5.1.1 All Law enforcement officers must use a taser prior to resorting to a lethal weapon and exceptions to this scenario.</p>
    </div>
  );
}