import React from "react";

export function ImmunityCodeContent() {
  return (
    <div className="lawyer-code-content criminal-code-content font-merriweather space-y-3">
      <div className="flex justify-center mb-6">
        <img src="/Legislation/DOJ Logo.png" alt="DOJ Logo" className="h-48 w-auto object-contain" />
      </div>
      <h1 className="text-[28px] font-bold text-center mb-2 text-black dark:text-white font-merriweather uppercase tracking-wide">CODE OF IMMUNITY AND PRIVILEGE</h1>
      <p className="text-[16px] font-normal text-center mb-8 text-[#5c6470] dark:text-[#9aa1b0] italic font-merriweather">(IMMUNITY CODE)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">THE CODE OF IMMUNITY AND SPECIAL STATUS LAW (IMMUNITY CODE)</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 1. General Provisions and Principles of Immunity Law</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.1</span>Code of Immunity and Special Status Law.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.1.1</span>This Code of Immunity and Special Status Law establishes the Principles of Legal Immunity and any Special Status that may be granted to a State Employee or Citizen in order to protect that Citizen from certain actions under the law and in order to facilitate the conduct of their Duties to the State of San Andreas.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.2</span>Rules and Principles of the Code of Immunity and Special Status Law.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.2.1</span>The Principles and Provisions of the Immunity and Status Law (Immunity Code) apply throughout the State of San Andreas and extends its legal force to all Citizens of the State who have been granted special provisions or protections under this Immunity Code and any interaction that may have with the State as a collective whole and other Citizens of the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>In the event of a conflict or a need for clarification between provisions of the Immunity Code and any other State Law, or a conflict of provisions within the Immunity Code itself, the Supreme Court shall make an Official Judicial Ruling as to the provisions that apply and the order of primacy of those provisions.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.2.2</span>Any Amendments to this Law by the Government or Judicial Rulings made by a Judge shall not apply retroactively and will only have force of law from the date of first application during a Trial or promulgation or publication as State Law.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>This Code replaces Articles 5 and 14 of the current Civil Code in their existing form as well as Repeals Civil Code 16.3.4 and 16.3.5 of the current Civil Code in their entirety and is published to Amend the outdated Provisions of Legal Immunity.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.3</span>Rules and Principles of Legal Immunity.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.1</span>Legal Immunity is a legal status wherein a State Employee who has been granted Legal Immunity is given certain protections from Civil and/or Criminal Liability to protect them from Procedural Actions that would limit their ability to make difficult decisions that may be necessary to perform their Duties to the State of San Andreas.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.2</span>Legal Immunity is defined by the Type of Immunity that a State Employee has for their Rank as detailed on the State Issued Identification within the State of San Andreas and may include:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Full Legal Immunity (also referred to as First Person Immunity)</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Partial Immunity (also referred to as Federal Immunity).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Judicial Immunity.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.3.3</span>The Form(s) of any Legal Immunity granted to any Citizen must clearly be defined within the Laws of the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Rank as given on their State Issued Identification (ID) must clearly state the State Employees Department and Rank and must clearly indicate a position within the State that is granted a Form of Legal Immunity (eg: a Role in an State Organisation email does not grant any form of Legal Immunity).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Protection(s) granted to a State Employee by any Form of Legal Immunity must clearly be defined and stated within the Law.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.4</span>Expectations and Rules of Conduct for First Persons.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.1</span>A State Employee with Full Legal Immunity (First Person) is a Senior State Official and represents their State Organisation and the State while On-Duty and is expected to conduct themselves and dress in a manner befitting of their status and responsibilities to the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Rules for the Conduct by a First Person are presented here as a List of Canon that sets out the expectations that all First Persons should follow.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.2</span>Any First Person who repeatedly conducts themselves in a manner unbefitting of their status shall be considered for an Order of Waiver (OW) that shall remove their Full Legal Immunity or shall be subject to an Order of Investigation (OI) and a resulting Impeachment Hearing for Misconduct held by the Governor, at least one Deputy Governor, and the Attorney General. Code of Conduct for First Persons</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Canon 1. First Persons shall not unlawfully abuse their Immunity Status and shall not repeatedly violate the law because they know they cannot be held liable for that particular violation of the law.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>First Persons shall not flaunt their Status as a First Person nor shall a First Person use any protections granted to them in an unethical or unprofessional manner.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Canon 2. First Persons are expected to set an example to all State Employees in the conduct and performance of their Duties to the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>First Persons shall conduct themselves in a professional manner with the Citizens of the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>First Persons shall conduct themselves in a professional manner with all Employees of the State.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Canon 3. First Persons are expected to respect the authority of other First Persons of the State in their conduct and performance of their Duties to the State.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>First Persons shall conduct themselves in a professional manner with the Governor, his appointed Deputy Governors and other Senior Representatives of the Government of the State and shall comply with the lawful orders of the Governor at all times.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A First Person shall conduct themselves in a professional manner with Leaders and Deputy Leaders of all other State Organisations and shall respect the Duties and Authority of those State Organisations and their Employees.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>First Persons shall conduct themselves in a professional manner with the Senior Representatives of the Department of Justice (DOJ) and shall respect their authority over the Justice System of the State.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>A First Person shall cooperate with the lawful orders of the Attorney General and the Judges while they are performing their Duties to the State as well as to comply with any valid Legal Documents as issued by the Court.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>A First Person shall not act in a manner to obstruct an Investigation by the Department of Justice (DOJ) and must cooperate with the lawful orders of the Attorney General and the Court during an Investigation.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Canon 4. First Persons are required to dress in a professional manner that is appropriate to their position as a First Person when performing any of their Official Duties to the State (eg: a meeting with the Governor) or to dress according to the Duties currently being performed (eg: a Tactical Uniform for a Raid).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A First Person shall comply with the General Dress Code regulations as set out in the Labour Code but is otherwise free to determine their own Uniforms unless otherwise indicated by the Leader of their State Organisation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A First Person shall comply with the regulations for Tattoos and Accessories as set out in the Labour Code.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>A First Person of the Government (eg: a Senior Civil Servant such as the Head of the Treasury) is not required to wear a Uniform while On-Duty and may request from the Governor permission to wear personal clothing (eg: a business suit) that is befitting of their Rank and Role within the Government.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Canon 5. First Persons are expected to respect the Property of the State and to use that Property only to perform their Duties to the State.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 2 Definitions in Immunity Law.</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.1</span>Definition of Full Legal Immunity (First Person Immunity)</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.1</span>Full Legal Immunity is defined as a legal status wherein an individual cannot be held liable for a minor criminal offence or other conduct that would otherwise impede the performance of their Duties to the State or cause them to not act in the interests of the State where those actions may result in Liability for their conduct of those actions.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.2</span>Full Legal Immunity Status in the State of San Andreas is given to the following Senior Government Officials of the State of San-Andreas which includes:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Governor of the State of San Andreas.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Deputy Governor(s).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The Attorney General.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>The Supreme Court Judges.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>The District Court Judges.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">f)</span>The Director of the United States Secret Service (USSS).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">g)</span>The Head of a Department of Government.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The Governor may determine the name used for a Head of Department according to their Rank structure of the Government.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.3</span>Full Legal Immunity Status in the State of San Andreas is also extended to the Leadership of the State Organisations (but not Private Organisations) within the State of San Andreas, which includes:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Leader of a State Organisation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Deputy Leader(s) of a State Organisation.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.1.4</span>If any Citizen of the State claims to be a First Person or claims they have Full Legal Immunity they must immediately show their Badge/ID in order to prove their Claim.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>If a Citizen does not immediately prove their Claim that they are a First Person when it is required then no provisions of Full Immunity Status will apply and they may be Detained until their Identity and status of Full Legal Immunity is proved.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.2</span>Definition of Partial Immunity (Federal Immunity).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.2.1</span>Partial (Federal) Immunity is defined as a limited form of Legal Immunity that is granted to all Federal Law Enforcement Officers in order to limit interference in the conduct of their lawful duties to the State.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.2.2</span>Partial Immunity only applies to the following Federal Law Enforcement Organisations and Departments of the Government:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Federal Investigation Bureau (FIB).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The United States Secret Service (USSS).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The Department of Justice (DOJ).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.2.3</span>In order to qualify for Partial Immunity, the State Issued Identification (ID) must clearly state their State Organisation (FIB) or Government Branch/Department (DOJ/USSS).</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">2.3</span>Definition of Judicial Immunity.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.1</span>Judicial Immunity is defined as a special form of Legal Immunity that is granted to all Senior Judicial Authorities in the State of San Andreas which protects from liability while making necessary judicial decisions.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.2</span>Judicial Immunity only applies to the following Department of Justice (DOJ) Senior Representatives:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Attorney General.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Supreme Court Judges.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The District Court Judges.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">2.3.3</span>In order to qualify for Judicial Immunity, the State Issued Identification (ID) must clearly state one of the above Ranks.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 3 Full Legal Immunity (First Person Immunity)</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">3.1</span>Definition and Protections Under Full Legal Immunity (First Person Immunity).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">3.1.1</span>Full Legal Immunity grants certain Protections to First Persons in order to ensure that they are free to perform their Duties to the State and to protect them from actions or conduct that may be necessary in the conduct of those Duties.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Protection from Criminal Liability. A Citizen with Full Legal Immunity Status (First Person) cannot be held Criminally Liable and Imprisoned for Class-1 Felony Crimes (★) or Class-2 Crimes (★★) or Misdemeanours under the Code of Criminal and Misdemeanour Law unless that Crime is clearly committed with Criminal Intent to Cause Harm to a Citizen (eg: a First Person is not Immune to Assault with Intent to Cause Harm).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Protection from Civil Liability. A Citizen with Full Legal Immunity (First Person) cannot be held Personally Liable for a Civil Case (Tort Case or Lawsuit) for actions or conduct that is part of their reasonably expected Duties to the State.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>A First Person who was acting in performance of their reasonably expected duties to the State is instead against the State or their State Organisation, unless the conduct of the First Person harmed the Rights of the Citizen without reasonable or lawful cause (eg: an Unlawful Termination of Employment without any valid reason).</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>Persons with Full Legal Immunity Status still have Civil Liability for any Civil Cases (Tort Cases and Lawsuit) while they are acting in their Private Capacity (eg: Off-Duty or not performing their Official Duties to the State).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Protection from Traffic Penalties. A Citizen with Full Legal Immunity (First Person) is Immune to Traffic Fines or Penalties.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>Protection from Unauthorised Detention. A Citizen with Full Legal Immunity Status (First Person) cannot be Detained without an Order of Investigation (OI) or a Direct Order given by the Governor or the Attorney General and only where there are lawful Grounds for the Detention.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>Protection from Unauthorised Search. Citizens with Full Legal Immunity Status (First Person) and their Personal Vehicles or Property cannot be Searched without an Order of Investigation (OI) or their expressed Consent to the Search.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Any Evidence from an unlawful or unauthorised Search of a First Person shall be considered Inadmissible as Evidence.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">f)</span>Protection from Unauthorised Investigation. Full Legal Immunity grants protection against any Investigation that is not authorised under the requirements of this Immunity Code.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>No Investigation against a Citizen with Full Legal Immunity Status (First Person) is permitted without an approved Order of Investigation (OI).</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>A Case File may only be opened against a Citizen with Full Legal Immunity (First Person) once an Order of Investigation (OI) has been approved by the Supreme Court.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">g)</span>Protection and Personal Safety. A Citizen with Full Legal Immunity Status (First Person) has the right to request a Protection Detail and/or Motorcade from the United States Secret Service (USSS) to assist with the performance of their Duties to the State or for their Personal Protection.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>Any Official Motorcade for a Citizen with Full Legal Immunity Status (First Person) is exempt from the Provisions of the Traffic Code so long as there are State Organisation Vehicles with Lights and Sirens Active at the front and back of the Motorcade.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">h)</span>Protection of Personal Information. A Citizen with Full Legal Immunity Status (First Person) has the right to be Classified upon application to the Federal Investigation Bureau (FIB).</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">1.4</span>Rules and Principles for the Application and Duration of Full Legal Immunity.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.1</span>Full Legal Immunity applies at all times, regardless of whether the First Person is On-Duty or Off-Duty.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A First Person is not considered “Always On-Duty” and is only considered On-Duty and obliged to perform their Duties to the State or respond to situations when they are formally On-Duty and therefore expected to perform those Duties.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">1.4.2</span>Full Legal Immunity and the protections granted by Full Legal Immunity are applied at the time of the Violation of the Law.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Full Legal Immunity cannot be granted to any Citizen in order to grant protection against any actions they committed prior to the granting of Full Legal Immunity (eg: they cannot be Hired, Promoted or Appointed to a position that has Full Legal Immunity to prevent legal actions).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Full Legal Immunity cannot be Waived or Removed by means other than those permitted in this Immunity Code (eg: they cannot be Blacklisted, Dismissed, Demoted or Suspended to remove Full Legal Immunity).</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 4. Partial Legal Immunity (Federal Immunity).</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">4.1</span>Rules and Protections Granted by Partial Legal Immunity (Federal Immunity)</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.1.1</span>Federal Immunity (also referred to as Partial Immunity) is defined as a form of Legal Immunity that aims to prevent interference in the conduct of Federal Law Enforcement duties.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Partial Immunity only applies while the State Employee with Federal Immunity is On-Duty and In-Uniform.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Partial Immunity does not apply to any State Employee who is working Undercover.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Partial Immunity or any other protection against Detention and/or Arrest granted to Federal Investigation Bureau (FIB) or United States Secret Service (USSS) Agents does not apply if the Agent is not engaged in the lawful conduct of their expected duties (eg: harassing other State Employees) or is clearly committing a Criminal Offence.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">4.1.2</span>Partial Immunity is limited in the protections granted to the above State Employees.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Protection from Detention. A State Employee with Federal Immunity may not be Detained or Questioned without the presence of a First Person of the State or a Higher Command of their State Organisation unless they have failed to Identify themselves when it is required.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Protection from Search. A State Employee with Federal Immunity may not be Searched without the presence of a First Person of the State or a Higher Command of their State Organisation unless there is a clear legal authority to do so at a State Facility (eg: USSS authority at the Capitol, DOC authority at the State Prison or by NG at Fort Zancudo).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Protection from Arrest. A State Employee with Federal Immunity has no protection from directly being Arrested if they have committed a Felony Crime in the presence of any Law Enforcement Officer(s) and Federal Immunity provides no protections against Arrest, Questioning while under Arrest or a lawful Search while under Arrest.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 5. Judicial Immunity (Judges Immunity)</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">5.1</span>Rules and Protections Granted by Judicial Immunity.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.1.1</span>The purpose of Judicial Immunity is to prevent Liability for necessary Decisions, Verdicts and Conduct that seeks to uphold the Justice System of the State of San Andreas and to prevent doubt in the authority of the Court to make those Verdicts that are within their powers and jurisdiction as granted in State Law to impose on a Citizen and will, by the very nature of those Decisions and Verdicts, affect the Rights of a Citizen.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">5.1.2</span>Under the Protections of Judicial Immunity, the following protections are granted:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Protection of Advisory Counsel. The Attorney General is the Chief Legal Advisor to the Government and the State of San Andreas and is required to provide legal advice to the Governor and his Government and State Organisations in a fair and balanced manner however any final determinations of the outcome of any legal dispute is determined by the Court and the legal advice given by the Attorney General cannot be considered final nor may liability be incurred for provision of any legal advice by the Attorney General in the performance of this Duty.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Protection of Judicial Privilege. As Judicial Officials must, by the nature of their duties, engage with Citizens who are either under Investigation, making Appeals to the Court or may be Wanted by the State, a State Employee with Judicial Immunity cannot be held criminally liable for any conduct or actions with the clear objective to uphold that Citizens Right to Justice.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Protection of Judicial Authority. In order to prevent a Judge from failing to give an appropriate Verdict and Punishments for any conduct or crimes that should be reasonably be given to a Suspect based on the facts as presented to the Court, State Employee with Judicial Immunity are Immune from Civil Liability for Decision and Verdicts performed within their reasonably expected duties to the Justice System of the State (eg: presiding over a Trial in Court) so long as the Decision or Verdict is both lawful and reasonable given the Evidence and Arguments presented in Court.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>This shall not apply to a Decision or Verdict that is given with clear criminal intent or are otherwise unlawful or unreasonable.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>Where a Decision or Verdict is to be contested, it shall be considered for an Appeal by a higher legal authority (The Attorney General, a Supreme Court Judge or the Supreme Court).</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 6. Procedural Actions Against Persons With Full Legal Immunity</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">6.1</span>Authority Regarding Applications to the Supreme Court and Investigations.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.1.1</span>The following Senior State Officials are the Heads of the State or a Federal Law Enforcement Organisation and therefore have the authority to apply directly to the Supreme Court for Procedural Actions against a First Person with Full Immunity.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Governor of the State of San Andreas (GOV).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Attorney General (USAGO).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The Director of the Federal Investigation Bureau (FIB).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.1.2</span>Where a Supreme Court Judge is under Investigation, the Governor and the Attorney General shall ensure that there are at least two other Supreme Court Judges who can act as the Supreme Court.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.1.3</span>Federal Law Enforcement Organisations or the following Departments of the Government (GOV) have the authority to conduct an Investigation into a Citizen with Full Legal Immunity only once an Order of Investigation (OI) has been granted by the Supreme Court.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Department of Justice (DOJ).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Department of Homeland Security (DHS).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>The United States Secret Service (USSS).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>The Federal Investigation Bureau (FIB).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.1.4</span>State Law Enforcement Organisations (LSPD/SAHP) or the National Guard (NG) have no authority or jurisdiction to conduct an Investigation into a State Official with Full Legal Immunity and must refer the all Evidence directly to one (or more) of the Senior State Officials (above) that have the necessary authority and/or jurisdiction.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>State Law Enforcement Organisations (LSPD/SAHP) or the National Guard (NG) may assist with the Investigation only if granted the jurisdiction or authority to do so within the Order of Investigation (OI).</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">6.2</span>Procedural Actions Against Citizens with Full Legal Immunity (First Persons).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.2.1</span>Any Investigation or Criminal Prosecution against a Citizen with Full Legal Immunity (First Person) first requires authorisation which must be granted by the Supreme Court.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.2.2</span>Based on the Case File and Evidence presented, the Supreme Court shall take one or more of the following actions:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Authorise Further Investigation. If the Supreme Court determines that further Investigation is authorised based on the Evidence presented, they shall Register the Case File and shall issue an Order of Investigation (OI) immediately.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The Order of Investigation (OI) must be provided to the First Person who is subject to the Investigation during any Detention, Questioning and/or Search to prove that these actions are lawful.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>The First Person may contest the Order of Investigation (OI) by a Motion to the Supreme Court however until a Verdict on the Motion is given, the Order of Investigation (OI) remains in effect.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Authorise Immunity Removal (Waiver). If the Supreme Court determines that an abuse of Full Legal Immunity has taken place but there is no clear evidence of a crime, they shall Register the Case File and shall issue an Order of Waiver (OW) immediately.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The First Person must be notified immediately that their Legal Immunity and all protections under Full Legal Immunity have been removed.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>The First Person must be provided the Order of Waiver (OW) immediately to prove that their Full Legal Immunity has been removed.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iii)</span>The First Person may contest the Order of Waiver (OW) by a Motion to the Supreme Court however until a Verdict on the Motion is given, their Immunity remains Waived.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iv)</span>In order to reinstate their Full Legal Immunity Status the Order of Waiver (OW) must be repealed by the Supreme Court or the period of Suspension of Immunity as stated in the Order of  Waiver (OW) must have passed.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>Authorise Criminal Indictment. If the Supreme Court determines that a Criminal Prosecution is authorised based on the Evidence presented, they shall Register the Case File and shall issue an Order of Investigation (OI) and the Criminal Indictment (CI) immediately.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>The First Person named in the Criminal Indictment (CI) must be notified of the Criminal Indictment (CI) within 48-hours of the alleged crime(s) to allow for any Bodycam or Evidence to be retained for their Defence.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">ii)</span>The Order of Investigation (OI) must be provided to the First Person named in the Case File as soon as possible and within 48-hours of the alleged crimes.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">iii)</span>The Criminal Indictment (CI) must be provided to the First Person named in the Criminal Indictment (CI) as soon as possible and within 48-hours of the alleged crimes.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>Dismiss the Case. Where no Investigation, Waiver or Indictment is warranted based on the Evidence and Arguments presented, or where no Liability could be applied, the Supreme Court shall dismiss the Application with clearly stated reasons and grounds for the dismissal.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">6.3</span>Detention and/or Arrest of a Citizen with Full Legal Immunity.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.3.1</span>In the event that a Citizen with Full Legal Immunity (First Person) is Detained, Searched or Arrested without the necessary Legal Documentation to Authorise the Procedural Action(s) or a clear lawful order from the Governor or the Attorney General, they must be immediately Released once their Identity and Status as a Citizen with Full Legal Immunity (First Person) is established.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Any Detention or Arrest of a  Citizen with Full Legal Immunity (First Person) shall not be considered unlawful or a Violation of Procedure if their Identity is not known at the time of Detention.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>Any Search of a  Citizen with Full Legal Immunity (First Person) shall be considered Inadmissible Evidence unless an Order of Investigation (OI) has been issued against the First Person.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.3.2</span>It is the responsibility of a  Citizen with Full Legal Immunity (First Person) who has been Detained and/or Arrested to cooperate with the Law Enforcement Officer(s) in a professional manner.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>They must Inform any Law Enforcement Officers present as to their Identity and Status of Full Legal Immunity.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>They must prove their Identity with a show of their State Issued ID when it is safe or reasonable to do so.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>If they do not cooperate or show their State Issued ID, the Law Enforcement Officer may keep them Detained until their Identification and Status as a Citizen with Full Legal Immunity (First Person) is proved.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">6.3.3</span>A Citizen with Full Legal Immunity (First Person) may not be Arrested and Processed into the Department of Corrections (DOC) unless one of the following applies:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>There is a Signed Order of Full Immunity Waiver (OW) that has removed their Full Legal Immunity Status prior to the Detention and/or Arrest and the First Person has committed the Crime(s) while no longer having Full Legal Immunity Status.</p>
      <p className="mb-3 text-justify pl-12 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">i)</span>A Senior Representative of the Department of Justice (DOJ) must still approve of the Charges as per the Labour Law and the Procedures for the Arrest of a State Employee.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>There is a Signed Special Warrant of Arrest (SWA) issued against the Citizen with Full Legal Immunity (First Person) that both authorises the Arrest and the Charges.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 7. Legal Documentation for Legal Immunity Cases</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">7.1</span>Order of Investigation (OI).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.1.1</span>Order of Investigation (OI) is issued by the Supreme Court or the Legal Immunity Review Board in order to both order an Investigation and grant the authority to investigate any Criminal Offence that has been committed by a Citizen with Full Legal Immunity (First Person).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.1.2</span>The Order of Investigation must be Signed by the Applicant for the Order of First Person Investigation and the Supreme Court and must further include:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>It shall contain the Name of the Person that is under Investigation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>It shall contain the Passport of the Person that is under Investigation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>It shall contain the Badge/ID of the Person that is under Investigation.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>It shall grant the Attorney General and the Judges of the Supreme Court the authority to conduct any reasonable actions towards an Investigation, Hearing or Trial.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>It shall grant the Bearer of the Order of Investigation (OI) the authority to conduct any reasonable actions towards an Investigation, Hearing or Trial.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.1.3</span>An Order of First Person Investigation is required to be issued before any Case File is registered or any further Investigation, Hearing or Trial is permitted against a Citizen with Full Legal Immunity (First Person).</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.1.4</span>An Order of First Person Investigation results in the First Person being Declassified immediately on presentation of the Order of Investigation (OI) to the Director of the Federal Investigation Bureau (FIB).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Any Classified Status is immediately removed by an Order of Investigation (OI) and any Evidence and Documents against the First Person that are necessary for the Investigation or Trial cannot be claimed to be Classified or concealed from any Lawyer who is Party to the Case or Trial on the basis that the person(s) are Classified.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Classified Status shall not be reinstated until the conclusion of the Investigation, Hearing or Trial or the Case File is formally closed by Verdict of the Court.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.1.5</span>An Order of Investigation (OI) shall expire after 30-days from the Date and Time of Signing of the Order.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">7.2</span>Order of Waiver (OW).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.2.1</span>An Order of Waiver (OW) is issued by the Supreme Court in order to formally remove the Full Legal Immunity Status from a Citizen with Full Legal Immunity (First Person).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>An Order of Full Immunity Waiver (OW) immediately removes the Full Legal Immunity Status from the First Person.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>An Order of Full Immunity Waiver (OW) immediately removes their Classified Status on notification to the Director of the Federal Investigation Bureau (FIB).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>An Order of Full Immunity Waiver (OW) is required in order to issue a Special Warrant of Arrest (SWA) as the Full Legal Immunity Status must first be removed by the Supreme Court, before the Warrant fully authorises the Arrest.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.2.2</span>The Order must be Signed by the Applicant for the Order of Full Immunity Waiver (OW) and must be Signed by the Supreme Court and must further include:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>It shall contain the Name of the Person whose Full Legal Immunity is to be Waived.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>It shall contain the Passport of the Person whose Full Legal Immunity is to be Waived.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>It shall contain the Badge/ID of the Person whose Full Legal Immunity is to be Waived.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>It shall clearly state the Grounds on which the Supreme Court has decided to remove the Full Legal Immunity Status.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>It shall include the Evidence used in the decision to remove the Full Legal Immunity Status.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.2.3</span>An Order of Full Immunity Waiver (OW) shall expire after 30-days from the Date and Time of Signing of the Order.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">7.3</span>Special Warrant of Arrest (SWA).</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.3.1</span>A Special Warrant Arrest (SWA) is issued against a Citizen with Full Legal Immunity (First Person) in order to authorise their Arrest and to indicate the Charges, Term of Imprisonment and any Fines and Penalties that shall be imposed.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A Special Warrant of Arrest (SWA) is not required if the Person named in the Warrant has already had their Legal Immunity removed by an Order of Waiver (OW) prior to a Criminal Charge and Direct Warrant of Arrest (DWA) may be used by any Law Enforcement Officer.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.3.2</span>The Special Warrant Arrest (SWA) shall be signed by  the Applicant for the Special Warrant of Arrest (SWA)  and the Supreme Court and shall contain:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Name of the Person who is to be Arrested.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Passport of the Person who is to be Arrested</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>It shall command that the Person be Arrested</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>It shall indicate the Charges of which the Person has been found Guilty.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">e)</span>It shall include the Evidence for the Charges.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">f)</span>It shall indicate the total Prison Term, Fines and any additional punishments that shall apply for those Charges.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">7.3.3</span>A Special Warrant of Arrest (SWA) must be enforced as soon as reasonably possible and shall expire after 30-days from the time of Signing if it has not been enforced.</p>

      <h2 className="text-[20px] font-bold mt-10 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather">Article 8. Rules and Principles of Classified Status</h2>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">8.1</span>The Status of Classified.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.1.1</span>The Personal Data of Citizens with Classified Status must be kept secret by all State Employees and the Federal Investigation Bureau (FIB).</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>Personal Data only includes any information that is not public knowledge (eg: Contact Details, Ownership of Property, Vehicles owned) and that the Citizen who is Classified has not themselves shared publicly.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.1.2</span>The Status of Classified does not grant any additional privileges, or any Rights that are in direct violation of the law or would constitute an Obstruction of Justice.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A Person who is Classified, must identify themselves to an appropriate authority such as a Law Enforcement Officer or Civil Servant of the State when required and shall not refuse on the grounds that they are Classified.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>A Person who is Classified must identify themselves when Detaining and/or Arresting a Suspect if asked and may not refuse on the Grounds that they are Classified.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>A Person who is Classified cannot use their Classified Status as Grounds to refuse to provide Evidence to a Lawyer during the Detention and/or Arrest of a Citizen.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">d)</span>A Person who is Classified cannot use their Classified Status as Grounds to refuse to provide Evidence to the Attorney General or the Supreme Court if that Evidence is required to be presented as Evidence in a Hearing or Trial or is a Record of the conduct of their Official Duties to the State that requires Bodycam Evidence to be recorded.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.1.3</span>In the event that any Person is discovered to be Classified and there are no Grounds for them to be Classified, the Federal Investigation Bureau (FIB) must be informed and the Person must immediately be Declassified.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>A Civilian may not be Classified for any reason and must be Declassified immediately by the Federal Investigation Bureau (FIB) on request.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">8.2</span>Persons with the Status of Classified.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.2.1</span>All First Persons of the State shall be Classified immediately by the Federal Investigation Bureau (FIB) upon application and direct proof of their Rank.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.2.2</span>Only the following State Officials have the authority to Classify or Declassify a Citizen:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Director of the Federal Investigation Bureau (FIB)</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The Deputy Directors of the Federal Investigation Bureau (FIB)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.2.3</span>It is the responsibility of the Director of the Federal Investigation Bureau (FIB) and their Deputies to update and maintain a List of Classified Persons which must include:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The Passport of the Person who is granted Classified Status.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>The State ID of the Person who is granted Classified Status.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.2.4</span>Where it is determined by the Governor, Attorney General or the Supreme Court that the List of Classified Persons is being mismanaged or there is clear and valid reason to believe that the List of Classified Persons is out of date or inaccurate:</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>All Persons who are Classified shall be Declassified by the Federal Investigation Bureau (FIB) or the appropriate Higher Authorities.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">b)</span>All Persons who should be Classified shall be notified that they must contact the FIB for Reclassification.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">c)</span>All Persons who have a right to be Classified shall be Reclassified as soon as possible with the presentation of their Passport and State Issued ID as Evidence and Proof of their Right to be Classified.</p>

      <h3 className="text-[17px] font-bold mt-6 mb-2 text-black dark:text-white font-merriweather"><span className="font-bold text-black dark:text-white mr-2">8.3</span>Restriction or Suspension of Classified Status.</h3>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.3.1</span>In the event that any person who is Classified loses their status of Full Legal Immunity or subject to an Order of Investigation (OI), they shall also be removed from the Classified List.</p>
      <p className="mb-3 text-justify pl-8 font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">a)</span>The FIB is obligated to monitor the timely application of Classified Status, as well as the removal of Classified Status, once they have been informed as to a change in status.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">8.3.2</span>Where PDA Evidence is required for a Case File or Investigation into a First Person, the Federal Investigation Bureau (FIB) is required to Declassify the Citizen immediately on presentation of an Order of Investigation (OI) that has been Signed by the Supreme Court.</p>

      <div className="text-center mt-12 mb-8 font-merriweather border-t border-black/20 dark:border-white/20 pt-8">
        <p className="text-black dark:text-white font-bold text-[18px] uppercase tracking-wider mb-6">Signed into Legislation By</p>
        <div className="my-6">
          <p className="font-dancing text-black dark:text-white text-[32px] leading-none mb-1">Dante Lasombra Attorney General of the State of San Andreas Tom Clinton Governor of the State of San Andreas</p>
        </div>
      </div>

      <h2 className="text-[20px] font-bold mt-12 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather text-center">Credit and Copyright</h2>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">This work, and the others in this series of legislative enhancement are produced and promulgated in the interests of justice and the promotion of the legal rights of all citizens of the State of San Andreas. First Edition Written, Revised and Amended in the 8th Month of 2025 by Attorney General Dante Lasombra and with the assistance of Supreme Court Judges Leo Malone and Vincent Vega in order to address outstanding issues with Immunity Law and to provide clear procedures and protections to First Persons and to ensure that any First Person who engages in unlawful conduct and abuse of Immunity can be held accountable</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">Dante Lasombra</p>

      <h2 className="text-[20px] font-bold mt-12 mb-4 text-black dark:text-white border-b border-black/20 dark:border-white/20 pb-2 font-merriweather text-center">Version History and Changes</h2>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]">First Edition. Published on the 18th of August 2025.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Major Change 1. Legal Immunity Review Board (LIRB) has been removed from the Immunity Law by agreement of the Supreme Court. It has hardly ever been used and is exceedingly difficult to take anything before the Immunity Board or to have all Leaders meet.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Major Change 2. Any Immunity Law case can be applied for directly to the Supreme Court by the Governor, the Attorney General or the Director of the FIB. Having only the Attorney General able to do this in the past has acted as an obstruction of justice if the Attorney General is not active or is negligent in taking actions.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 1.1 and 1.2 as Preamble to the Code of Immunity Law in keeping with standard format for all Codes of Law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added a) to clarify that the Immunity Code replaces any existing Immunity Law Provisions in the Civil Code</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 1.3 to clarify the types of Immunity that exist and how it can be proved and the requirements for protections.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 2 for Definitions as per all other Codes of Law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.1 Added Definition of Full Legal Immunity (First Person Immunity) and who has Full Immunity. Clarified g) That it is the Head of a Department of Government. The name does not matter as the terms Minister or Secretary can be used depending on the Governor.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.1.3 to grant Full Immunity to the Deputies of State Organisations as this has been requested repeatedly.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.1.4 to prevent false Claims to have Full Legal Immunity.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.2 for Definition of Partial Immunity</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.2.2 Clarified that it only applies to FIB, USSS and DOJ.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.2.3 Clarified that the ID must clearly state the Organisation or Department. Roles in email were being used/abused to grant half an organisation Partial Immunity and this is not longer permitted.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.3 for Definition of Judicial Immunity</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.2.2 Clarified that it only applies to the Attorney General and the Judges.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 2.3.3 Clarified that the ID must clearly state the Organisation or Department.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 3 for Full Legal Immunity</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 3.1 for Principles and Protections under Full Legal Immunity.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 4 for Partial Immunity (Federal Immunity)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 4.1 to Clarify when Partial Immunity applies.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 4.1.2 to Clarify the Protections granted by Partial Immunity and to indicate that Partial Immunity does not protect a State Employee from Arrest if they have directly committed a crime in the presence of Law Enforcement Officers.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 5 for Judicial Immunity.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 5.1 for the Rules and Protections granted by Judicial Immunity.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 5.1.2 a) to Clarify that Legal Advice by the Attorney General is not a guarantee as Judicial Decisions are made by the Court.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 5.1.2 b) to Clarify that a Judge must be able to engage with persons who are Appealing Cases or Wanted Status and cannot be Charged for upholding Justice.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 5.1.2 c) to Clarify that a Judge cannot be liable for giving a Verdict unless that Verdict is clearly criminal in the intent or outcomes.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 6 for Procedural Actions against First Persons.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.1 Authority to Apply to the Supreme Court</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.1.1 and Removed the Immunity Review Board and granted the authority to take Immunity Cases to the Supreme Court Governor, Attorney General and the Director of FIB.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.1.2 to address the issue where a Supreme Court Judge is under Investigation.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.1.3 to Clarify who is permitted to perform the Investigation once the Order is approved.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.1.4 to Clarify procedures for LSPD/SAHP/NG to resolve matters of Full Immunity and when they are permitted to assist with an Investigation.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.2 for Procedural Actions Against Citizens with Full Legal Immunity (First Persons)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.2.2 a) the Supreme Court may authorise an Investigation</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.2.2 b) the Supreme Court may authorise a Waiver to removed Immunity</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.2.2 a) the Supreme Court may authorise an Indictment for the Charges</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.2.2 a) the Supreme Court may dismiss the Case</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.3.1 for situations where a First Person is Detained or Arrested</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.3.2 a First Person is required to act professionally and cooperate and must show their Identification.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 6.3.3 Clarified when a First Person can be Arrested and Processed into the DOC.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 7 Legal Documentation for Immunity Cases</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 7.1 the Order of Investigation (OI) with requirements</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 7.2 the Order of Waiver (OW)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 7.3 the Special Warrant of Arrest (SWA)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added Article 8 Classified Status</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 8.1.1 to Clarify exactly what Classified means by the Law.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 8.1.2 to Clarify that Classified or a claim to be classified cannot be used as an Obstruction of Justice.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 8.2 to Clarify that First Persons have a right to be Classified.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(18/08/2025)</span>Added 8.2.4 to Unclassify all Persons where the List is being mismanaged or needs to be reset. Additional Amendments to First Edition. Published on the 5th of September 2025.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Changed 1.2.1 Fixed wording error (repeated words)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Changed 1.2.2 Fixed Numbering error (not bold)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Changed 1.3.1 Clarified as applying only to a State Employee.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>1.3.3 Clarified that a Role in the email does not grant any Partial Legal Immunity. Half of LSPD and SAHP are made SWAT in the email just to grant Partial Immunity which the DOJ will not uphold. This has resulted in the SAHP removing all major Departments except SAHP (everyone) and SWAT in their Charter.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Amended 1.2.2 a) Clarified that the Immunity Code also replaces Civil Code 16.3.4 and 16.3.5 which have been used by USSS and FIB to obstruct justice as to require the AG to be present just to detain USSS or FIB for any Investigation is completely unreasonable. These Provisions are included here for reference and are a legacy of where the Civil Code was a set of separate Codes that were inherited at the founding of our City.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">16.3.4</span>The reason for the detention of a USSS employee is an order from the Attorney General issued to the FIB employees.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">16.3.5</span>The reason for the detention of an FIB officer is an order from the Attorney General issued to the USSS.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added 1.4.1 Expectations and Rules of Conduct for First Persons as per request.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added 1.4.2 Added provision for punishments or Impeachment Hearings for violations of the Code of Conduct for First Persons (Impeachment is a Hearing for Misconduct and is not a Criminal Matter but if necessary be referred to the Supreme Court by the Governor or the AG)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added Code of Conduct for First Persons (Rules for Conduct under US Law are referred to as Canon)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added Canon 1. Rule for abusing Immunity Protections</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added Canon 2. Rule for professional conduct</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added Canon 3. Rule for respecting the authority of other First Persons (Governor, Leaders and DOJ)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added Canon 4. Rule for dressing appropriately and according to the situation (eg: smart for meeting the Governor or Court Appearances, tactical gear for a raid etc)</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added Canon 5. Rule for respecting State Property.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>Added 2.1.2 e) and fixed letter allocation afterwards. Following discussion with the Supreme Court, District Court Judges should have Full Legal Immunity as the requirements to qualify as a District Court Judge are difficult and they should be protected in the law. This will also correct the problem where the Government only makes people SCJs for the Full Legal Immunity and have no DCJs.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>4.1.1 c) Clarified that the protections against Detention and/or Arrest do not apply to FIB/USSS who are not conducting their lawful duties or are clearly committing a crime (this also overrules and clarifies Civil Code 16.3.4 and 16.3.5) as that only applies to Detaining not direct Arrest.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>5.1.2 b) Clarified as State Employee</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(30/08/2025)</span>5.1.2 c) Clarified as State Employee</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(06/09/2025)</span>Added Sub-Provision a) to Canon 1 that a First shall not flaunt the fact that they are a First Person.</p>
      <p className="mb-3 text-justify font-merriweather leading-relaxed text-[#5c6470] dark:text-[#9aa1b0]"><span className="font-bold text-black dark:text-white mr-2">(06/09/2025)</span>Added 1.4.1 and renumbered following provision to 1.4.2 to clarify that a First Person is NOT always on duty and Sub-Provision a) to clarify when they are considered On-Duty and expected to perform their duties.</p>
    </div>
  );
}